# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mk < Formula
  desc "Multi-Kubectl: Run kubectl commands on multiple contexts"
  homepage "https://github.com/suminhong/multi-kubectl"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suminhong/multi-kubectl/releases/download/v0.0.4/mk_0.0.4_darwin_amd64.tar.gz"
      sha256 "209d2eb723f0dabb3f920089db42c3442103271d311ad3d13e33721ad1644476"

      def install
        bin.install "mk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suminhong/multi-kubectl/releases/download/v0.0.4/mk_0.0.4_darwin_arm64.tar.gz"
      sha256 "2a2c5549512864111a97b6e11d1c3a9e13a7667f728d8cc570430e0cef95349b"

      def install
        bin.install "mk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suminhong/multi-kubectl/releases/download/v0.0.4/mk_0.0.4_linux_amd64.tar.gz"
      sha256 "328002d9f3ebcf2c158b4f5569c4fe11c878b78f3b335c6f04b85d1c66917f90"
      def install
        bin.install "mk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suminhong/multi-kubectl/releases/download/v0.0.4/mk_0.0.4_linux_arm64.tar.gz"
      sha256 "06e5d1fd8a4f24c38681e8f25c8f233131e31d8c85656ee404b50484dacb9196"
      def install
        bin.install "mk"
      end
    end
  end
end
