# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mk < Formula
  desc "Multi-Kubectl: Run kubectl commands on multiple contexts"
  homepage "https://github.com/suminhong/multi-kubectl"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suminhong/multi-kubectl/releases/download/v0.0.8/mk_0.0.8_darwin_amd64.tar.gz"
      sha256 "dc9e59dec927dc332780295f7fc7017950515ac7e6c47dd19979463ebebc1830"

      def install
        bin.install "mk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suminhong/multi-kubectl/releases/download/v0.0.8/mk_0.0.8_darwin_arm64.tar.gz"
      sha256 "eeff63858b268124c79dddb2749d272a766cc0a0a854dea8ccf5abdd2ff8b6be"

      def install
        bin.install "mk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suminhong/multi-kubectl/releases/download/v0.0.8/mk_0.0.8_linux_amd64.tar.gz"
      sha256 "61d45c6979996696be35a10153763f9c0862d041b414283febee90b8cefa902d"
      def install
        bin.install "mk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suminhong/multi-kubectl/releases/download/v0.0.8/mk_0.0.8_linux_arm64.tar.gz"
      sha256 "0b275962536d41c19ff98abfdde9c5461b5b6cda946000a15c7741ce10b77c4e"
      def install
        bin.install "mk"
      end
    end
  end
end
